# Generated by Django 3.2.9 on 2023-07-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230513_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
