# Generated by Django 3.2.9 on 2023-08-02 12:52

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20230513_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('pic', models.ImageField(upload_to='articles')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=255, unique=True, verbose_name='Slug')),
                ('views', models.PositiveIntegerField(default=0)),
                ('catgory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category')),
                ('tags', models.ManyToManyField(blank=True, to='courses.Tag')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=220)),
                ('content', tinymce.models.HTMLField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.article')),
            ],
            options={
                'verbose_name': 'article Translation',
                'db_table': 'courses_article_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
