# Generated by Django 3.2.9 on 2023-08-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_article_articletranslation_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='catgory',
            new_name='category',
        ),
    ]
