# Generated by Django 3.2.9 on 2023-08-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tawjihi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_categroy', models.CharField(blank=True, choices=[('Bac', 'Bac'), ('Jihawi', 'Jihawi'), ('Tawjih', 'Tawjih'), ('Concours', 'Concours')], max_length=20, null=True)),
                ('title', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('field_of_Study', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Canceled', 'Canceled'), ('Waiting', 'Waiting')], default='Waiting', max_length=10)),
                ('contacted', models.BooleanField(default=False)),
                ('tawgihi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation.tawjihi')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
